=== ruivale/Java/JDK1.8Examples/src/exp/xml/parsing/XmlDoUser.dtd
<!-- Elementos relativos ao utilizador -->
<!ELEMENT User (Name, Application*)>
<!ELEMENT Application (Name,Class,GIMenu,GIToolBar)>

<!-- Elementos relativos às aplicações -->
<!ELEMENT GIMenu (Menu*)>
<!ELEMENT Menu (Name,(MenuItem* | Menu*)*)>
<!ELEMENT MenuItem (Name,Class,Method,Arg*)>
<!ELEMENT GIToolBar (ToolBar)>
<!ELEMENT ToolBar (ToolBarItem*)>
<!ELEMENT ToolBarItem (Name,Class,Method,Arg*)>

<!-- Elementos  relativos às operações -->
<!ELEMENT GI (GITree)>
<!ELEMENT GITree (Network)>
<!ELEMENT Network (Node*)>
<!ELEMENT Node (Name, X, Y, Width, Equipment*)>
<!ELEMENT Equipment (Name, Properties*)>
<!ELEMENT Eq_properties (Name, Class, Operation*)>
<!ELEMENT Operation (Name, Method, Arg*)>

<!-- Elementos gerais -->
<!ELEMENT Name (#PCDATA)>
<!ELEMENT X (#PCDATA)>
<!ELEMENT Y (#PCDATA)>
<!ELEMENT Width (#PCDATA)>
<!ELEMENT Class (#PCDATA)>
<!ELEMENT Method (#PCDATA)>
<!ELEMENT Arg (#PCDATA)>

<!-- Atributos relativos ao user -->
<!ATTLIST User
id CDATA #REQUIRED
>
<!-- Atributos relativos ás aplicações -->
<!ATTLIST Application
id CDATA #REQUIRED
perm CDATA #REQUIRED
>

<!-- Atributos relativos aos menus das IGs -->
<!ATTLIST MenuItem
id CDATA #REQUIRED
>
<!ATTLIST Menu
id CDATA #REQUIRED
>

<!-- Atributos relativos à barra de ferramentas das IGs -->
<!ATTLIST ToolBarItem
id CDATA #REQUIRED
>

<!-- Atributos relativos à árvore da rede das IGs -->
<!ATTLIST Network
id CDATA #REQUIRED
>
<!ATTLIST Node
id CDATA #REQUIRED
>
<!ATTLIST Equipment
id CDATA #REQUIRED
>
<!ATTLIST Properties
id CDATA #REQUIRED
>
<!ATTLIST Operation
id CDATA #REQUIRED
perm CDATA #REQUIRED
>

=== ruivale/Java/JDK1.8Examples/src/exp/xml/parsing/XmlDoUser.xml
<?xml version="1.0"?>
<!DOCTYPE User SYSTEM "XmlDoUser.dtd">
<User id="8927">
  <Name>A. Monteiro</Name>
  <Application id="3232" perm="w">
    <Name>PIS</Name>
    <Class>com.ent.PIS.pis</Class>
    <GIMenu>
      <Menu>
        <Name>Ajuda</Name>
        <MenuItem id="122">
          <Name>Aplicação</Name>
          <Class>com.ent.PIS.Help</Class>
          <Method>applicationHelp</Method>
       </MenuItem>
      </Menu>
      <Menu>
        <Name>Ficheiros</Name>
        <Menu>
          <Name>Sair</Name>
          <MenuItem id="192">
            <Name>Sair da applicação</Name>
            <Class>com.ent.PIS.pis</Class>
            <Method>exit</Method>
          </MenuItem>
        </Menu>
      </Menu>
    </GIMenu>
    <GIToolBar>
      <ToolBar>
        <ToolBarItem id="837283">
            <Name>Sair da applicação</Name>
            <Class>com.ent.PIS.pis</Class>
            <Method>exit</Method>
        </ToolBarItem>
      </ToolBar>
    </GIToolBar>
  </Application>
  <Application id="756" perm="r">
    <Name>STV</Name>
    <Class>com.ent.STV.stv</Class>
    <GIMenu>
      <Menu>
        <Name>Ficheiro stv</Name>
        <MenuItem id="1619">
          <Name>Sair</Name>
          <Class>com.ent.STV.stv</Class>
          <Method>exit</Method>
        </MenuItem>
        <Menu>
          <Name>Gravar</Name>
          <MenuItem id="1112">
            <Name>Gravar informação</Name>
            <Class>com.ent.STV.stv</Class>
            <Method>recInfo</Method>
          </MenuItem>
        </Menu>
    </Menu>
    </GIMenu>
    <GIToolBar>
      <ToolBar>
        <ToolBarItem id="837283">
            <Name>Sair da applicação</Name>
            <Class>com.ent.STV.stv</Class>
            <Method>exit</Method>
        </ToolBarItem>
      </ToolBar>
    </GIToolBar>
  </Application>
</User>
